 # import the lib

In [1]:
import numpy as np 

 #  Array in numpy 

In [2]:
a = np.array([1, 2, 3])
a


array([1, 2, 3])

Access the elements using array indexes 

In [3]:
print(a[0])

1


Add some data to a numpy array

In [4]:
a[0] = 22 
a

array([22,  2,  3])

slicing 

In [5]:
a[1:3]

array([2, 3])

In [6]:
b = np.array([[1,2,3],[5,6,7],[8,9,10]])
b

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [7]:
b[2,2]

np.int64(10)

Array attributes 

The number of dimensions of an array is contained in the ndim attribute.

In [8]:
b.ndim

2

The shape of an array is a tuple of non-negative integers that specify the number of elements along each dimension.

In [9]:
b.shape

(3, 3)

In [10]:
b.size

9

To check the data type of the array

In [11]:
b.dtype

dtype('int64')

#  How to create a basic array

This section covers np.zeros(), np.ones(), np.empty(), np.arange()

Besides creating an array from a sequence of elements, you can easily create an array filled with 0’s

In [12]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

Or an array filled with 1’s:

In [13]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

Create an empty array with 2 elements

In [14]:
np.empty((2,2))

array([[1., 1.],
       [1., 1.]])

You can create an array with a range of elements:

In [15]:
np.arange(4)

array([0, 1, 2, 3])

 # Adding, removing, and sorting elements

 np.sort(), np.concatenate()

In [16]:
array = np.array([9,36,7,836,78,22,96,100])

To sort the elements the array

In [17]:
array = np.sort(array)
array

array([  7,   9,  22,  36,  78,  96, 100, 836])

For concatenate two array

In [18]:
a = np.array([1,2,3,4,5])
b = np.array([6,7,8,9,10])

In [19]:
np.concatenate((a,b))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

#  Can you reshape an array?

In [20]:
a = np.arange(6)
print(a)

[0 1 2 3 4 5]


In [21]:
b = a.reshape(3, 2)
print(b)

[[0 1]
 [2 3]
 [4 5]]


In [22]:
b.shape

(3, 2)

#  Indexing and slicing

In [23]:
data = np.array([1, 2, 3])
data

array([1, 2, 3])

In [24]:
data[1]

np.int64(2)

In [25]:
data[0:2]

array([1, 2])

In [26]:
data[1:]

array([2, 3])

In [27]:
data[-2:]

array([2, 3])

In [28]:
a2 = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [29]:
print(a2[a2 < 5])

[1 2 3 4]


In [30]:
divisible_by_2 = a[a%2==0]
print(divisible_by_2)

[0 2 4]


# How to create an array from existing data

This section covers slicing and indexing, np.vstack(), np.hstack(), np.hsplit()

In [31]:
a = np.array([1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [32]:
a = a[3:8]
print(a)

[4 5 6 7 8]


In [33]:
a1 = np.array([[1, 1],
               [2, 2]])

a2 = np.array([[3, 3],
               [4, 4]])

You can stack them vertically with vstack:

In [34]:
np.vstack((a1, a2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

Or stack them horizontally with hstack

In [35]:
np.hstack((a1, a2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

# Basic array operations

In [36]:
data = np.array([1, 2])
ones = np.ones(2, dtype=int)
data + ones

array([2, 3])

In [37]:
a = np.array([[1,2,3],[4,5,6]])
a.sum()

np.int64(21)

In [38]:
b = np.array([[1, 1], [2, 2]])

In [39]:
b.sum(axis=0)

array([3, 3])

In [40]:
b.sum(axis=1)

array([2, 4])

 # Broadcasting

In [41]:
data = np.array([1.0, 2.0])
data * 1.6

array([1.6, 3.2])

In [42]:
data.min()

np.float64(1.0)

In [43]:
data.max()

np.float64(2.0)

In [44]:
data.sum()

np.float64(3.0)

# More useful array operations

In [45]:
a = np.array([[0.45053314, 0.17296777, 0.34376245, 0.5510652],
              [0.54627315, 0.05093587, 0.40067661, 0.55645993],
              [0.12697628, 0.82485143, 0.26590556, 0.56917101]])

In [46]:
a.sum()

np.float64(4.8595784)

In [47]:
a.min()

np.float64(0.05093587)

In [48]:
a.min(axis=0)

array([0.12697628, 0.05093587, 0.26590556, 0.5510652 ])

#  Creating matrices

You can pass Python lists of lists to create a 2-D array (or “matrix”) to represent them in NumPy.

In [50]:
data = np.array([[1, 2], [3, 4], [5, 6]])
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [51]:
data[0, 1]

np.int64(2)

In [52]:
data[1:3]

array([[3, 4],
       [5, 6]])

#   Generating random numbers

In [54]:
rng = np.random.default_rng()
rng.integers(5, size=(2, 4)) 

array([[4, 2, 4, 0],
       [4, 4, 0, 1]])

In [84]:
a =  np.random.rand(3,2).round(2) * 100 

In [85]:
a.astype(int)

array([[12, 79],
       [28, 38],
       [64, 99]])

#   How to get unique items and counts

In [61]:
a = np.array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20])
a

array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20])

In [62]:
np.unique(a)

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

To get the indices of unique values in a NumPy array (an array of first index positions of unique values in the array), just pass the return_index argument in np.unique() as well as your array

In [64]:
unique_values , indices_list  = np.unique( a, return_index=True )
print(indices_list)

[ 0  2  3  4  5  6  7 12 13 14]


You can pass the return_counts argument in np.unique() along with your array to get the frequency count of unique values in a NumPy array.

In [65]:
unique_values, occurrence_count = np.unique(a, return_counts=True)
print(occurrence_count)

[3 2 2 2 1 1 1 1 1 1]


#   Transposing and reshaping a matrix

This section covers arr.reshape(), arr.transpose(), arr.T

In [67]:
data = np.array([[1,2],[3,4],[5,6]])
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [68]:
data.reshape(2, 3)

array([[1, 2, 3],
       [4, 5, 6]])

In [69]:
data.reshape(3, 2)

array([[1, 2],
       [3, 4],
       [5, 6]])

You can transpose your array with arr.transpose().

In [70]:
data.transpose()

array([[1, 3, 5],
       [2, 4, 6]])

You can also use arr.T:

In [71]:
data.T

array([[1, 3, 5],
       [2, 4, 6]])

#   How to reverse an array

This section covers np.flip()

In [72]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

In [77]:
reversed_arr = np.flip(arr)

In [78]:
print('Reversed Array: ', reversed_arr)

Reversed Array:  [8 7 6 5 4 3 2 1]


In [79]:
arr_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [80]:
np.flip(arr_2d)

array([[12, 11, 10,  9],
       [ 8,  7,  6,  5],
       [ 4,  3,  2,  1]])