 # import the lib

In [46]:
import numpy as np 

 #  Array in numpy 

In [47]:
a = np.array([1, 2, 3])
a


array([1, 2, 3])

Access the elements using array indexes 

In [6]:
print(a[0])

1


Add some data to a numpy array

In [8]:
a[0] = 22 
a

array([22,  2,  3])

slicing 

In [11]:
a[1:3]

array([2, 3])

In [14]:
b = np.array([[1,2,3],[5,6,7],[8,9,10]])
b

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [20]:
b[2,2]

np.int64(10)

Array attributes 

The number of dimensions of an array is contained in the ndim attribute.

In [21]:
b.ndim

2

The shape of an array is a tuple of non-negative integers that specify the number of elements along each dimension.

In [22]:
b.shape

(3, 3)

In [23]:
b.size

9

To check the data type of the array

In [24]:
b.dtype

dtype('int64')

#  How to create a basic array

This section covers np.zeros(), np.ones(), np.empty(), np.arange()

Besides creating an array from a sequence of elements, you can easily create an array filled with 0’s

In [29]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

Or an array filled with 1’s:

In [30]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

Create an empty array with 2 elements

In [31]:
np.empty((2,2))

array([[1., 1.],
       [1., 1.]])

You can create an array with a range of elements:

In [34]:
np.arange(4)

array([0, 1, 2, 3])

 # Adding, removing, and sorting elements

 np.sort(), np.concatenate()

In [35]:
array = np.array([9,36,7,836,78,22,96,100])

To sort the elements the array

In [38]:
array = np.sort(array)
array

array([  7,   9,  22,  36,  78,  96, 100, 836])

For concatenate two array

In [40]:
a = np.array([1,2,3,4,5])
b = np.array([6,7,8,9,10])

In [41]:
np.concatenate((a,b))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

#  Can you reshape an array?

In [43]:
a = np.arange(6)
print(a)

[0 1 2 3 4 5]


In [44]:
b = a.reshape(3, 2)
print(b)

[[0 1]
 [2 3]
 [4 5]]


In [45]:
b.shape

(3, 2)